# Generated by Django 5.2.8 on 2025-12-04 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=200)),
                ('item_desc', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=6)),
                ('item_image', models.URLField(default='https://imgcdn.stablediffusionweb.com/2024/10/14/b4676dd8-6fef-4df9-9a4c-5d1c72155b40.jpg', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['item_name', 'item_price'], name='myapp_item_item_na_8fffba_idx')],
            },
        ),
    ]
