# Generated by Django 5.2.6 on 2025-11-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Iems_name',
            new_name='Item_name',
        ),
    ]
