# Generated by Django 5.2.6 on 2025-11-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_iems_name_items_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Item_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=50),
        ),
    ]
