# Generated by Django 5.2.6 on 2025-11-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_image',
            field=models.CharField(default='https://imgcdn.stablediffusionweb.com/2024/10/14/b4676dd8-6fef-4df9-9a4c-5d1c72155b40.jpg', max_length=500),
        ),
    ]
