# Generated by Django 5.2.6 on 2025-11-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
