# Generated by Django 5.2.6 on 2025-11-27 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_category_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_image',
            field=models.URLField(default='https://imgcdn.stablediffusionweb.com/2024/10/14/b4676dd8-6fef-4df9-9a4c-5d1c72155b40.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
