# Generated by Django 5.2.6 on 2025-11-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_item_created_at_item_is_active_alter_item_item_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item_desc',
            new_name='item_desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Item_image',
            new_name='item_image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Item_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Item_price',
            new_name='item_price',
        ),
    ]
