# Generated by Django 5.2.8 on 2025-11-30 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_item_item_name_alter_item_item_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_name', 'item_price'], name='myapp_item_item_na_8fffba_idx'),
        ),
    ]
